name: Auto Merge Dependabot PRs

on:
  pull_request_target:
    types:
    - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && github.event.label.name == 'auto-merge'
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2.6
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        command: "squash and merge"
        approve: true
        target: minor
